# Generated by Django 5.1.7 on 2025-04-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcode',
            options={'verbose_name': '은행 코드', 'verbose_name_plural': '은행 코드 목록'},
        ),
    ]
